openapi: 3.2.0
info:
  title: NewSkies-Digital-Api E Tickets API
  version: 4.8.6.23
  description: Navitaire Digital Api
servers:
- url: https://prod.api.tui/flight/newskies/rest
  description: TUI Prod
- url: https://playground.api.tui/flight/newskies/rest
  description: TUI Playground
security:
- JWT: []
tags:
- name: eTickets
paths:
  /api/nsk/v2/eTickets/{eTicketNumber}:
    get:
      tags:
      - eTickets
      summary: 'Retrieves the passenger''s e-ticket and its details by providing the ticket number,

        hosted carrier code and the alternate carrier code from the e-ticket database

        if the ticket is OA validated (issued by the other airline not by the hosted carrier).'
      description: 'GraphQL endpoint: eTicketv3'
      operationId: nsk_v2_eTickets_eTicketNumber_get
      parameters:
      - name: eTicketNumber
        in: path
        required: true
        description: The e-ticket number.
        schema:
          type: string
        x-position: 1
      - name: HostedCarrierCode
        in: query
        description: "The hosted carrier code. If not provided, the hosted carrier code will be retrieved internally.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 2
      - name: AlternateCarrierCode
        in: query
        description: "The alternate carrier code. This is required if the ticket is issued by another airline.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 3
      responses:
        '200':
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfETicketResponsev2'
              examples:
                Initially issued e-tickets:
                  description: Example response for successful retrieval of issued e-tickets
                  value:
                    eTicket:
                      passengerName:
                        first: Example
                        middle: null
                        last: Passenger
                        title: null
                        suffix: null
                      connectedETickets:
                      - couponCount: 1
                        ticketNumber: 0286010103190
                        ticketEmds: null
                      exchangedETickets: []
                      recordLocators:
                      - recordLocatorKey: Vzk0SFVHIQa--
                        recordCode: ABCDEF
                        systemDomainCode: null
                        owningSystemCode: null
                        bookingSystemCode: NV
                        interactionPurpose: null
                        hostedCarrierCode: null
                      fareCalculation: SLC NV BOS84.65USD84.65END
                      issueDate: '2026-07-09T00:00:00Z'
                      companyIdNumber: '0000'
                      chargeCode: null
                      totalTaxAmount: 25.0
                      taxDetailsList:
                      - taxCode: CGY
                        amount: 20.0
                        currencyCode: USD
                      ticketFare:
                        baseAmount: 150.0
                        currencyCode: USD
                        foreignAmount: 0.0
                        foreignCurrencyCode: null
                      totalAmount: 200.0
                      totalAmountCurrencyCode: USD
                      remarks:
                      - textQualifier: 3
                        informationType: 10
                        freeTexts:
                        - THIS COMMENT IS FOR VOLUNTARY ISSUANCE OF E TICKET
                      - textQualifier: 3
                        informationType: 12
                        freeTexts:
                        - SLC NV BOS84.65USD84.65END
                      - textQualifier: 3
                        informationType: 13
                        freeTexts:
                        - SALT LAKE CITY US
                        - NAV1 DEFAULT CARRIER
                      - textQualifier: 3
                        informationType: 14
                        freeTexts:
                        - SLC10NOV231234567
                      createdUserIdentifier: '45321'
                    status: 1
                    alternateCarrierCode: NV
                Re-issued e-tickets:
                  description: Example response for successful retrieval of re-issued e-tickets
                  value:
                    eTicket:
                      passengerName:
                        first: Example
                        middle: null
                        last: Passenger
                        title: null
                        suffix: null
                      connectedETickets:
                      - couponCount: 1
                        ticketNumber: 0286010103191
                        ticketEmds: null
                      exchangedETickets:
                      - couponCount: 1
                        ticketNumber: 0286010103190
                        ticketEmds: null
                      recordLocators:
                      - recordLocatorKey: Vzk0SFVHIQa--
                        recordCode: ABCDEF
                        systemDomainCode: null
                        owningSystemCode: null
                        bookingSystemCode: NV
                        interactionPurpose: null
                        hostedCarrierCode: null
                      fareCalculation: SLC NV BOS84.65USD84.65END
                      issueDate: '2026-07-09T00:00:00Z'
                      companyIdNumber: '0000'
                      chargeCode: null
                      totalTaxAmount: 25.0
                      taxDetailsList:
                      - taxCode: CGY
                        amount: 20.0
                        currencyCode: USD
                      ticketFare:
                        baseAmount: 150.0
                        currencyCode: USD
                        foreignAmount: 0.0
                        foreignCurrencyCode: null
                      totalAmount: 200.0
                      totalAmountCurrencyCode: USD
                      remarks:
                      - textQualifier: 3
                        informationType: 10
                        freeTexts:
                        - THIS COMMENT IS FOR INVOLUNTARY ISSUANCE OF E TICKET
                      - textQualifier: 3
                        informationType: 12
                        freeTexts:
                        - SLC NV BOS84.65USD84.65END
                      - textQualifier: 3
                        informationType: 13
                        freeTexts:
                        - SALT LAKE CITY US
                        - NAV1 DEFAULT CARRIER
                      - textQualifier: 3
                        informationType: 14
                        freeTexts:
                        - ' 0286010103190  SLC10NOV231234567'
                      createdUserIdentifier: '45321'
                    status: 1
                    alternateCarrierCode: NV
        '400':
          description: There was a problem with the request and it could not be completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
              examples:
                Non-existent e-Ticket:
                  description: Example error when retrieving non-existent or invalid e-tickets
                  value:
                    errors:
                    - id: null
                      code: nsk:ETicket:ETicketNotFoundInETicketDatabase
                      message: nsk:ETicket:ETicketNotFoundInETicketDatabase
                      type: Error
                      details: null
                      rawMessage: The e-ticket number 0286010103199 was not found in the e-ticket database.
                      exception: null
                      debugMode: The API is currently running in debug mode. In production the 'rawMessage' and 'exception' nodes will not be returned. These are for troubleshooting development issues only.
                    data: null
        '404':
          description: The item was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/nsk/v1/eTickets/{eTicketNumber}/coupons:
    get:
      tags:
      - eTickets
      summary: Retrieves all coupons associated with the e-ticket.
      description: 'GraphQL endpoint: eTicketCouponsv2'
      operationId: nsk_v1_eTickets_eTicketNumber_coupons_get
      parameters:
      - name: eTicketNumber
        in: path
        required: true
        description: The e-ticket number.
        schema:
          type: string
        x-position: 1
      - name: HostedCarrierCode
        in: query
        description: "The hosted carrier code. If not provided, the hosted carrier code will be retrieved internally.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 2
      - name: AlternateCarrierCode
        in: query
        description: "The alternate carrier code. This is required if the ticket is issued by another airline.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 3
      responses:
        '200':
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfIListOfETicketCoupon'
        '404':
          description: The item was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/nsk/v1/eTickets/{eTicketNumber}/coupons/{couponNumber}:
    get:
      tags:
      - eTickets
      summary: Retrieves a single coupon associated with the e-ticket.
      description: 'GraphQL endpoint: eTicketCouponv2'
      operationId: nsk_v1_eTickets_eTicketNumber_coupons_couponNumber_get
      parameters:
      - name: eTicketNumber
        in: path
        required: true
        description: The e-ticket number.
        schema:
          type: string
        x-position: 1
      - name: couponNumber
        in: path
        required: true
        description: The e-ticket coupon number.
        schema:
          type: integer
        x-position: 2
      - name: HostedCarrierCode
        in: query
        description: "The hosted carrier code. If not provided, the hosted carrier code will be retrieved internally.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 3
      - name: AlternateCarrierCode
        in: query
        description: "The alternate carrier code. This is required if the ticket is issued by another airline.\n            "
        schema:
          type:
          - string
          - 'null'
        x-position: 4
      responses:
        '200':
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfETicketCoupon'
        '404':
          description: The item was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/nsk/v2/eTickets/{eTicketNumber}/coupons/{couponNumber}:
    put:
      tags:
      - eTickets
      summary: Updates a coupon contained in an e-ticket.
      description: 'GraphQL endpoint: eTicketCouponSetv3'
      operationId: nsk_v2_eTickets_eTicketNumber_coupons_couponNumber_put
      parameters:
      - name: eTicketNumber
        in: path
        required: true
        description: The e-ticket number to update.
        schema:
          type: string
        x-position: 1
      - name: couponNumber
        in: path
        required: true
        description: The coupon number to update
        schema:
          type: integer
        x-position: 2
      requestBody:
        x-name: request
        description: The e-ticket coupon update request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateETicketCouponRequestBase'
        required: true
        x-position: 3
      responses:
        '200':
          description: OK. Request completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfUpdateETicketCouponResponse'
        '404':
          description: The item was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
components:
  schemas:
    TransportationIdentifier:
      type: object
      description: "Represents the transportation identifier model data.\n            "
      additionalProperties: false
      required:
      - identifier
      - carrierCode
      properties:
        identifier:
          type: string
          description: "The unique transportation identifier.\n            "
          maxLength: 4
          minLength: 0
        carrierCode:
          type: string
          description: "The carrier code.\n            "
          maxLength: 3
          minLength: 2
        opSuffix:
          type:
          - string
          - 'null'
          description: "The op suffix.\nPlease note that this should be a char and not a string.\n            "
          maxLength: 1
    InformationType:
      type: integer
      description: "Defines the information type of the remarks in an e-ticket.\n            \n\n0 = Unknown\n1 = FlifoExists\n2 = Address\n3 = BusinessTelephoneNumber\n4 = HomeTelephoneNumber\n5 = TelephoneNatureUnknown\n6 = TravelAgentTelephoneNumber\n7 = Remarks\n8 = ReferenceIndication\n9 = TicketNumber\n10 = EndorsementInformation\n11 = CommissionInformation\n12 = FareCalculationOnTicketing\n13 = IssuingNameAndPlace\n14 = OriginalIssueInformation\n15 = IssueReasonSubCodeDescription"
      x-enumNames:
      - Unknown
      - FlifoExists
      - Address
      - BusinessTelephoneNumber
      - HomeTelephoneNumber
      - TelephoneNatureUnknown
      - TravelAgentTelephoneNumber
      - Remarks
      - ReferenceIndication
      - TicketNumber
      - EndorsementInformation
      - CommissionInformation
      - FareCalculationOnTicketing
      - IssuingNameAndPlace
      - OriginalIssueInformation
      - IssueReasonSubCodeDescription
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
    WeightType:
      type: integer
      description: "Weight Type enumeration.\n            \n\n0 = Default\n1 = Pounds\n2 = Kilograms"
      x-enumNames:
      - Default
      - Pounds
      - Kilograms
      enum:
      - 0
      - 1
      - 2
    UpdateETicketCouponRequestBase:
      type: object
      description: "Represents a request for updating coupons from within an e-ticket.\n            "
      additionalProperties: false
      properties:
        hostedCarrierCode:
          type:
          - string
          - 'null'
          description: "The hosted carrier code. If not provided, the hosted carrier code will be retrieved internally.\n            "
        alternateCarrierCode:
          type:
          - string
          - 'null'
          description: "The alternate carrier code. This is required if the ticket is issued by another airline.\n            "
        oaValidatingCarrier:
          type:
          - string
          - 'null'
          description: "Validating carrier code.\n            "
          maxLength: 3
          minLength: 2
        comment:
          type:
          - string
          - 'null'
          description: "Comment text.\n            "
        isVoluntaryChange:
          type: boolean
          description: "Indicates a voluntary change to the coupon or otherwise.\n            "
        updateFunction:
          description: "Indicates the type of update function to be done in the coupon.\n            "
          $ref: '#/components/schemas/ETicketCouponUpdateFunction'
        status:
          description: "Indicates the new status for the coupon.\n            "
          $ref: '#/components/schemas/ETicketCouponStatusCode'
    RecordLocator:
      type: object
      description: "Defines a unique locator for reference.\n            "
      additionalProperties: false
      properties:
        systemDomainCode:
          type:
          - string
          - 'null'
          description: "The system domain code.\n            "
          maxLength: 3
          minLength: 0
        bookingSystemCode:
          type:
          - string
          - 'null'
          description: "The system code of where the booking was created.\n            "
          maxLength: 3
          minLength: 0
        hostedCarrierCode:
          type:
          - string
          - 'null'
          description: "The hosted carrier's code.\n            "
          maxLength: 3
          minLength: 0
        recordLocatorKey:
          type:
          - string
          - 'null'
          description: "The unique record locator key.\n            "
        recordCode:
          type:
          - string
          - 'null'
          description: "The record code.\n            "
          maxLength: 12
          minLength: 0
        owningSystemCode:
          type:
          - string
          - 'null'
          description: "The owning system code for the booking.\n            "
          maxLength: 3
          minLength: 0
        interactionPurpose:
          type:
          - string
          - 'null'
          description: "The interaction purpose.\n            "
          maxLength: 2
          minLength: 0
    BaggageAllowanceInfo:
      type: object
      description: "Represents baggage allowance information contained in an e-ticket.\n            "
      additionalProperties: false
      properties:
        quantity:
          type: integer
          description: "The baggage allowance quantity.\n            "
          format: int32
        type:
          description: "The baggage allowance type.\n            "
          $ref: '#/components/schemas/BaggageAllowanceType'
        weightType:
          description: "The baggage allowance unit / weight type.\n            "
          $ref: '#/components/schemas/WeightType'
    TicketStatusCode:
      type: integer
      description: "This enumeration defines the ticket availability status.\n            \n\n0 = Unknown\n1 = TicketAvailableForUse\n2 = TicketUnavailableForUse\n3 = TicketReissueRequiredForPassenger\n4 = TicketReissueRequiredForInfant\n5 = TicketReissueRequiredForBoth\n6 = TicketReValidationRequired"
      x-enumNames:
      - Unknown
      - TicketAvailableForUse
      - TicketUnavailableForUse
      - TicketReissueRequiredForPassenger
      - TicketReissueRequiredForInfant
      - TicketReissueRequiredForBoth
      - TicketReValidationRequired
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    PassengerTicketFare:
      type: object
      description: "Represents fare information for an e-ticket issued to a passenger.\n            "
      additionalProperties: false
      properties:
        baseAmount:
          type: number
          description: "The base fare amount of the e-ticket.\n            "
          format: decimal
        currencyCode:
          type:
          - string
          - 'null'
          description: "The base fare amount's currency code.\n            "
        foreignAmount:
          type: number
          description: "The base fare (excluding taxes, fees, and charges) in the collected currency.\n            "
          format: decimal
        foreignCurrencyCode:
          type:
          - string
          - 'null'
          description: "The foreign amount's currency code.\n            "
    BaggageAllowanceType:
      type: integer
      description: "Defines the baggage allowance type in a passenger e-ticket.\n            \n\n0 = Unknown\n1 = Weight\n2 = PerPiece\n3 = None"
      x-enumNames:
      - Unknown
      - Weight
      - PerPiece
      - None
      enum:
      - 0
      - 1
      - 2
      - 3
    Exception:
      type: object
      additionalProperties: false
      properties:
        Message:
          type: string
        InnerException:
          $ref: '#/components/schemas/Exception'
        Source:
          type:
          - string
          - 'null'
        StackTrace:
          type:
          - string
          - 'null'
    TextSubjectQualifier:
      type: integer
      description: "Defines the text subject qualifier of remarks in an e-ticket.\n            \n\n0 = Unknown\n1 = CodedFreeText\n2 = LiteralText\n3 = CodedAndLiteralText\n4 = ChangeInformation\n5 = ProductInformation\n6 = SafetyInformation\n7 = IataDefinedInformation\n8 = SpecialHandling\n9 = StatutoryNotice\n10 = TransportationInformation\n11 = MutuallyDefined"
      x-enumNames:
      - Unknown
      - CodedFreeText
      - LiteralText
      - CodedAndLiteralText
      - ChangeInformation
      - ProductInformation
      - SafetyInformation
      - IataDefinedInformation
      - SpecialHandling
      - StatutoryNotice
      - TransportationInformation
      - MutuallyDefined
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
    SeatingStatusCode:
      type: integer
      description: "Defines the seating status code for an e-ticket.\n            \n\n0 = Unknown\n1 = BookingConfirmed\n2 = NoSeat"
      x-enumNames:
      - Unknown
      - BookingConfirmed
      - NoSeat
      enum:
      - 0
      - 1
      - 2
    MessageStatus:
      type: integer
      description: "Defines the message status.\n            \n\n0 = General\n1 = Warning\n2 = Critical"
      x-enumNames:
      - General
      - Warning
      - Critical
      enum:
      - 0
      - 1
      - 2
    IJsonResponseOfETicketCoupon:
      type: object
      description: "Defines the JSON response contract.\n            "
      additionalProperties: false
      properties:
        data:
          description: "The payload data.\n            "
          $ref: '#/components/schemas/ETicketCoupon'
        errors:
          type:
          - array
          - 'null'
          description: "The collection of errors being thrown.\n            "
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          description: "The collection of informational messages.\n            "
          items:
            $ref: '#/components/schemas/Message'
    ETicketResponsev2:
      type: object
      description: "The response for retrieving and displaying e-ticket information.\n            "
      additionalProperties: false
      properties:
        eTicket:
          description: "The e-ticket which is equivalent to the New Skies passenger ticket.\n            "
          $ref: '#/components/schemas/PassengerTicketv2'
        status:
          description: "The status return code when retrieving e-tickets.\n            "
          $ref: '#/components/schemas/TicketReturnCode'
        alternateCarrierCode:
          type:
          - string
          - 'null'
          description: "The alternate carrier code. This is also known as the e-ticket database, or the carrier code of the issuing\nairline.\n            "
    ETicket:
      type: object
      description: "The base e-ticket model.\n            "
      additionalProperties: false
      properties:
        couponCount:
          type: integer
          description: "The number of coupons contained in the e-ticket.\n            "
          format: int32
        ticketNumber:
          type:
          - string
          - 'null'
          description: "The e-ticket number.\n            "
        ticketEmds:
          type:
          - array
          - 'null'
          description: "The associated EMDs to the e-ticket.\n            "
          items:
            type: string
    TicketReturnCode:
      type: integer
      description: "Defines the status or outcome of an e-ticket operation.\n            \n\n0 = Unknown\n1 = Success\n2 = TicketNotFound\n3 = NotAuthorized\n4 = IssueRetrievingTicket\n5 = NoETicketConfiguration"
      x-enumNames:
      - Unknown
      - Success
      - TicketNotFound
      - NotAuthorized
      - IssueRetrievingTicket
      - NoETicketConfiguration
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    Name:
      type: object
      description: "Defines a common name.\n            "
      additionalProperties: false
      properties:
        first:
          type:
          - string
          - 'null'
          description: "The given first name.\n            "
          maxLength: 32
          minLength: 0
        middle:
          type:
          - string
          - 'null'
          description: "The given middle name.\n            "
          maxLength: 32
          minLength: 0
        last:
          type:
          - string
          - 'null'
          description: "The given last name.\n            "
          maxLength: 32
          minLength: 0
        title:
          type:
          - string
          - 'null'
          description: "The title.\n            "
          maxLength: 6
          minLength: 0
        suffix:
          type:
          - string
          - 'null'
          description: "The suffix.\n            "
          maxLength: 6
          minLength: 0
    ETicketCoupon:
      type: object
      description: "The coupon on an e-ticket.\n            "
      additionalProperties: false
      properties:
        couponNumber:
          type:
          - integer
          - 'null'
          description: "The coupon number.\n            "
          maximum: 4.0
          minimum: 1.0
        marketInformation:
          description: "The market information of the coupon.\n            "
          $ref: '#/components/schemas/MarketInformation'
        classOfService:
          type:
          - string
          - 'null'
          description: "The class of service or booking class.\n            "
          maxLength: 8
          minLength: 0
        seatingStatusCode:
          description: "Status of the reservation. This column displays OK for adult and NS (No Seat) for infant in lap passengers.\n            "
          $ref: '#/components/schemas/SeatingStatusCode'
        fareBasisCode:
          type:
          - string
          - 'null'
          description: "Fare basis code and ticket designator.\n            "
        couponStatus:
          description: "The coupon status.\n            "
          $ref: '#/components/schemas/ETicketCouponStatusCode'
        notValidBefore:
          type:
          - string
          - 'null'
          description: "The travel validity before date.\n            "
          format: date-time
        notValidAfter:
          type:
          - string
          - 'null'
          description: "The travel validity after date.\n            "
          format: date-time
        baggageAllowance:
          description: "Contains the free baggage allowance.\n            "
          $ref: '#/components/schemas/BaggageAllowanceInfo'
        isArrivalUnknown:
          type: boolean
          description: "Indicates if the arrival information for the coupon is unknown (i.e., ARNK).\n            "
    ErrorResponse:
      type: object
      description: "Defines a unique error response.\n            "
      additionalProperties: false
      properties:
        exception:
          description: "The original exception that was thrown and all the exception details.\n            "
          $ref: '#/components/schemas/Exception'
        rawMessage:
          type:
          - string
          - 'null'
          description: "The original raw message set (non-localized).\n            "
        code:
          type:
          - string
          - 'null'
          description: "The unique error code. The primary value used to match against a unique message localized for the end user in the\nchosen language.\n            "
        message:
          type:
          - string
          - 'null'
          description: "The error message. Deprecated: Please use the Code instead.\n            "
        type:
          type:
          - string
          - 'null'
          description: "The error type showing severity. Values: Critical, Error, Validation, Information.\n            "
        number:
          type:
          - integer
          - 'null'
          description: "A unique identifier in numeric form. This is required for Splunk logging. If none is provided a number will be\ngenerated based on code and type.\n            "
          format: int32
          maximum: 99999.0
          minimum: 0.0
        details:
          type:
          - object
          - 'null'
          description: "Dynamic detailed information about the error.\n            "
          additionalProperties:
            type: string
        ActivityId:
          type:
          - string
          - 'null'
          description: "The activity ID unique to the request. Useful for debugging purposes to uniquely look up what happened for this\nspecific request.\n            "
    UpdateETicketCouponResponse:
      type: object
      description: "Represents a response from updating coupons from within an e-ticket.\n            "
      additionalProperties: false
      properties:
        status:
          description: "The status return code upon updating an e-ticket coupon.\n            "
          $ref: '#/components/schemas/TicketReturnCode'
        errorText:
          type:
          - string
          - 'null'
          description: "The error text from the e-ticket database, if the update resulted in an error.\n            "
        tickets:
          type:
          - array
          - 'null'
          description: "Indicates the detailed e-ticket information from the coupon update results.\n            "
          items:
            $ref: '#/components/schemas/PassengerTicketInfo'
    Message:
      type: object
      description: "Defines a unique informational message.\n            "
      additionalProperties: false
      properties:
        code:
          type:
          - string
          - 'null'
          description: "The unique message code.\n            "
        type:
          type:
          - string
          - 'null'
          description: "The message type.\n            "
        value:
          type:
          - string
          - 'null'
          description: "The message's value.\n            "
        status:
          description: "The message's status.\n            "
          $ref: '#/components/schemas/MessageStatus'
        details:
          type:
          - object
          - 'null'
          description: "Dynamic detailed information about the message.\n            "
          additionalProperties:
            type: string
    Remark:
      type: object
      description: "The fare calculation line associated to an e-ticket.\n            "
      additionalProperties: false
      properties:
        textQualifier:
          description: "The text qualifier.\n            "
          $ref: '#/components/schemas/TextSubjectQualifier'
        informationType:
          description: "The information type.\n            "
          $ref: '#/components/schemas/InformationType'
        freeTexts:
          type:
          - array
          - 'null'
          description: "The text pulled from the matching remark's list of free texts for the fare calculation.\nTypically the text needed is stored as the first value in the list.\n            "
          items:
            type: string
    ETicketCouponStatusCode:
      type: integer
      description: "Defines the e-ticket coupon status code.\n            \n\n0 = Unknown\n1 = OaControl\n2 = Flown\n3 = Boarded\n4 = CheckedIn\n5 = Exchanged\n6 = Open\n7 = NoSeat\n8 = Confirmed\n9 = Printed\n10 = Refunded\n11 = Requested\n12 = Suspended\n13 = SpaceAvailable\n14 = Ticketed\n15 = Voided\n16 = InfoOnly\n17 = IrregularOps\n18 = Unavailable\n19 = PrintExchanged\n20 = Closed\n21 = Override\n22 = ConvertedToFim\n23 = RefundTaxesFeesCharges"
      x-enumNames:
      - Unknown
      - OaControl
      - Flown
      - Boarded
      - CheckedIn
      - Exchanged
      - Open
      - NoSeat
      - Confirmed
      - Printed
      - Refunded
      - Requested
      - Suspended
      - SpaceAvailable
      - Ticketed
      - Voided
      - InfoOnly
      - IrregularOps
      - Unavailable
      - PrintExchanged
      - Closed
      - Override
      - ConvertedToFim
      - RefundTaxesFeesCharges
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
    IJsonResponseOfETicketResponsev2:
      type: object
      description: "Defines the JSON response contract.\n            "
      additionalProperties: false
      properties:
        data:
          description: "The payload data.\n            "
          $ref: '#/components/schemas/ETicketResponsev2'
        errors:
          type:
          - array
          - 'null'
          description: "The collection of errors being thrown.\n            "
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          description: "The collection of informational messages.\n            "
          items:
            $ref: '#/components/schemas/Message'
    MarketInformation:
      type: object
      description: "Model information about the market arrival and destination details.\n            "
      additionalProperties: false
      required:
      - destination
      - origin
      - departureDate
      - identifier
      properties:
        destination:
          type: string
          description: "Gets or sets the leg arrival station.\n            "
          maxLength: 3
          minLength: 0
        origin:
          type: string
          description: "Gets or sets the leg departure station.\n            "
          maxLength: 3
          minLength: 0
        departureDate:
          type: string
          description: "The departure date.\n            "
          format: date-time
          minLength: 1
        identifier:
          description: "Gets or sets the leg arrival station.\n            "
          $ref: '#/components/schemas/TransportationIdentifier'
    TaxDetails:
      type: object
      description: "The tax details for an e-ticket.\n            "
      additionalProperties: false
      properties:
        taxCode:
          type:
          - string
          - 'null'
          description: "The tax code.\n            "
        amount:
          type: number
          description: "The tax amount.\n            "
          format: decimal
        currencyCode:
          type:
          - string
          - 'null'
          description: "The currency code of the tax amount.\n            "
    PassengerTicketv2:
      type: object
      description: "Represents detailed information for an e-ticket issued to a passenger.\n            "
      additionalProperties: false
      properties:
        passengerName:
          description: "The passenger name.\n            "
          $ref: '#/components/schemas/Name'
        connectedETickets:
          type:
          - array
          - 'null'
          description: "The list of e-tickets issued to the passenger.\n            "
          items:
            $ref: '#/components/schemas/ETicket'
        exchangedETickets:
          type:
          - array
          - 'null'
          description: "The previous e-tickets when e-tickets were reissue for the booking.\n            "
          items:
            $ref: '#/components/schemas/ETicket'
        recordLocators:
          type:
          - array
          - 'null'
          description: "Record locators associated with the e-ticket.\n            "
          items:
            $ref: '#/components/schemas/RecordLocator'
        fareCalculation:
          type:
          - string
          - 'null'
          description: "The fare calculation. This property is redundant and the same information can be found on the Remarks property.\n            "
          deprecated: true
          x-deprecatedMessage: 4.4.4 - Please use Remarks instead.
        issueDate:
          type:
          - string
          - 'null'
          description: "The date the e-ticket was issued.\n            "
          format: date-time
        companyIdNumber:
          type:
          - string
          - 'null'
          description: "The company ID number of the service airline or system service provider.\n            "
        chargeCode:
          type:
          - string
          - 'null'
          description: "The non-numeric value for the e-ticket's total fare value.\n            "
        totalTaxAmount:
          type: number
          description: "The tax amount for the e-ticket.\n            "
          format: decimal
        taxDetailsList:
          type:
          - array
          - 'null'
          description: "The list of all tax details of the e-ticket.\n            "
          items:
            $ref: '#/components/schemas/TaxDetails'
        ticketFare:
          description: "The base fare represented in the e-ticket's currency code and foreign currency code.\n            "
          $ref: '#/components/schemas/PassengerTicketFare'
        totalAmount:
          type: number
          description: "The total amount for the e-ticket.\n            "
          format: decimal
        totalAmountCurrencyCode:
          type:
          - string
          - 'null'
          description: "The currency code of the total amount for the e-ticket.\n            "
        remarks:
          type:
          - array
          - 'null'
          description: "Additional information associated to the e-ticket.\n            "
          items:
            $ref: '#/components/schemas/Remark'
        createdUserIdentifier:
          type:
          - string
          - 'null'
          description: "The created user's identifier.\n            "
    IJsonResponseOfIListOfETicketCoupon:
      type: object
      description: "Defines the JSON response contract.\n            "
      additionalProperties: false
      properties:
        data:
          type:
          - array
          - 'null'
          description: "The payload data.\n            "
          items:
            $ref: '#/components/schemas/ETicketCoupon'
        errors:
          type:
          - array
          - 'null'
          description: "The collection of errors being thrown.\n            "
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          description: "The collection of informational messages.\n            "
          items:
            $ref: '#/components/schemas/Message'
    IJsonResponse:
      type: object
      description: "Defines the JSON response contract for a not content type response.\n            "
      additionalProperties: false
      properties:
        data:
          description: "The payload data, this will always be null for errors responses and no content responses.\n            "
        errors:
          type:
          - array
          - 'null'
          description: "The collection of errors being thrown.\n            "
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          description: "The collection of informational messages.\n            "
          items:
            $ref: '#/components/schemas/Message'
    IJsonResponseOfUpdateETicketCouponResponse:
      type: object
      description: "Defines the JSON response contract.\n            "
      additionalProperties: false
      properties:
        data:
          description: "The payload data.\n            "
          $ref: '#/components/schemas/UpdateETicketCouponResponse'
        errors:
          type:
          - array
          - 'null'
          description: "The collection of errors being thrown.\n            "
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          description: "The collection of informational messages.\n            "
          items:
            $ref: '#/components/schemas/Message'
    PassengerTicketInfo:
      type: object
      description: "Represents detailed information for an e-ticket assigned to a passenger.\n            "
      additionalProperties: false
      properties:
        status:
          description: "Ticket status.\n            "
          $ref: '#/components/schemas/TicketStatusCode'
        ticketIndicator:
          type:
          - string
          - 'null'
          description: "Ticket indicator.\n            "
        passengerCouponCount:
          type: integer
          description: "Number of passenger coupons affected.\n            "
          format: int32
        infantPassengerCouponCount:
          type: integer
          description: "Number of infant passenger coupons affected.\n            "
          format: int32
    ETicketCouponUpdateFunction:
      type: integer
      description: "Represents the function types used to update an e-ticket coupon.\n            \n\n0 = UpdateCouponStatus\n1 = ManualCouponStatusChange\n2 = RequestReturnControl\n3 = RequestAirportControl"
      x-enumNames:
      - UpdateCouponStatus
      - ManualCouponStatusChange
      - RequestReturnControl
      - RequestAirportControl
      enum:
      - 0
      - 1
      - 2
      - 3
  securitySchemes:
    JWT:
      type: http
      description: Paste your JWT token from the token endpoint.
      scheme: bearer
      bearerFormat: jwt
x-generator: NSwag v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))
