openapi: 3.2.0
info:
  title: NewSkies-GoNow-Api Legs API
  description: Navitaire GoNow Api
  version: 5.2.6.69
servers:
- url: https://prod.api.tui/flight/newskies/gonow
  description: TUI Prod
- url: https://playground.api.tui/flight/newskies/gonow
  description: TUI Playground
security:
- JWT: []
tags:
- name: legs
paths:
  /api/dcs/v1/legs:
    get:
      tags:
      - legs
      summary: Retrieves a list of inventory legs based on search criteria.
      description: 'GraphQL endpoint: dcsGetLegs'
      operationId: dcs_v1_legs_get
      parameters:
      - name: CarrierCode
        in: query
        schema:
          type:
          - string
          - 'null'
          maxLength: 3
          minLength: 2
        x-position: 1
      - name: DepartureDate
        in: query
        schema:
          type:
          - string
          - 'null'
          format: date-time
        x-position: 2
      - name: Origin
        in: query
        schema:
          type:
          - string
          - 'null'
          maxLength: 3
          minLength: 3
        x-position: 3
      - name: Destination
        in: query
        schema:
          type:
          - string
          - 'null'
          maxLength: 3
          minLength: 3
        x-position: 4
      - name: FlightNumber
        in: query
        schema:
          type:
          - string
          - 'null'
        x-position: 5
      - name: OpSuffix
        in: query
        schema:
          type:
          - string
          - 'null'
          maxLength: 1
          minLength: 0
        x-position: 6
      responses:
        '200':
          description: The list of inventory legs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfListOfLeg'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/gss/v1/legs/{legKey}/close/requirements:
    get:
      tags:
      - legs
      summary: Gets government security requirements that are required for closing the specified leg.
      description: 'GraphQL endpoint: dcsGetLegCloseSecurityRequirements'
      operationId: gss_v1_legs_legKey_close_requirements_get
      parameters:
      - name: legKey
        in: path
        required: true
        description: The unique leg key. Leg keys can be retrieved via GET /api/dcs/v1/legs.
        schema:
          type: string
        x-position: 1
      responses:
        '200':
          description: List of government security requirements that must be satisfied in order to close the specified flight leg.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfListOfLegCloseSecurityRequirement'
              examples:
                Success example:
                  description: An example 200OK Successful response.
                  value:
                    data:
                    - governmentProgram: USDHS
                      governmentProgramType: 1
                      programDescription: United States - SecureFlight
                      eligibleDocuments:
                      - typeCode: A
                        group: 2
                        typeName: Permanent Resident Card
                        isPrimary: false
                      - typeCode: C
                        group: 1
                        typeName: U.S. Alien Registration Card
                        isPrimary: false
                      - typeCode: F
                        group: 3
                        typeName: Facilitation Document
                        isPrimary: false
                      - typeCode: G
                        group: 18
                        typeName: Government ID card
                        isPrimary: false
                      - typeCode: M
                        group: 5
                        typeName: Military ID Card
                        isPrimary: false
                      - typeCode: P
                        group: 6
                        typeName: Permanent Resident Card
                        isPrimary: false
                      - typeCode: PD
                        group: 6
                        typeName: Diplomatic Passport
                        isPrimary: false
                      - typeCode: PM
                        group: 6
                        typeName: Missionary Passport
                        isPrimary: false
                      - typeCode: PS
                        group: 6
                        typeName: Special Passport
                        isPrimary: false
                      - typeCode: T
                        group: 17
                        typeName: Refugee Travel Document
                        isPrimary: false
                      - typeCode: V
                        group: 9
                        typeName: Travel Visa
                        isPrimary: false
                      documentRequiredFields:
                      - 6
                      - 9
                      - 10
                      - 0
                      - 2
                      additionalDataRequiredFields:
                      - 5
                      - 6
                      - 4
                      - 3
                      minVerifiedDocumentCount: 1
                      flightCloseCountryCodes:
                      - US
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
              examples:
                Invalid legKey:
                  description: Example error response when the leg key is invalid.
                  value:
                    errors:
                    - id: a70ddb46-fc1a-bed4-9ae9-b3c4eb6be908
                      code: legKey:InvalidApiKey
                      message: 'Invalid legKey: asdf'
                      type: Validation
                      details:
                        message: 'Invalid legKey: asdf'
                        param: legKey
                        validation: InvalidApiKey
                      rawMessage: null
                      exception: null
                      debugMode: The API is currently running in debug mode. In production the 'rawMessage' and 'exception' nodes will not be returned. These are for troubleshooting development issues only.
                    data: null
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/dcs/v1/legs/{legKey}/operationsInfo:
    get:
      tags:
      - legs
      summary: 'Retrieves operations (AKA flight following) info for the specified inventory leg.  In

        the case of passive flights, only status, boardingTimeOffset, and schedule-related

        fields are populated.'
      description: 'This endpoint replaces the dotREZ NSK API''s GET /api/nsk/v2/trip/info/{legKey}/status.

        This endpoint uses a more detailed and operationally-appropriate enum for the status

        field.


        GraphQL endpoint: dcsGetOperationsInfo'
      operationId: dcs_v1_legs_legKey_operationsInfo_get
      parameters:
      - name: legKey
        in: path
        required: true
        description: The leg key or manifest leg key.
        schema:
          type: string
        x-position: 1
      responses:
        '200':
          description: The operations info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfOperationsInfo'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
              examples:
                Invalid legKey:
                  description: Example error response when the leg key is invalid.
                  value:
                    errors:
                    - id: a70ddb46-fc1a-bed4-9ae9-b3c4eb6be908
                      code: legKey:InvalidApiKey
                      message: 'Invalid legKey: asdf'
                      type: Validation
                      details:
                        message: 'Invalid legKey: asdf'
                        param: legKey
                        validation: InvalidApiKey
                      rawMessage: null
                      exception: null
                      debugMode: The API is currently running in debug mode. In production the 'rawMessage' and 'exception' nodes will not be returned. These are for troubleshooting development issues only.
                    data: null
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
  /api/dcs/v1/legs/{legKey}/thruLegs:
    get:
      tags:
      - legs
      summary: Retrieves a list of thru legs for the specified leg.
      description: 'GraphQL endpoint: dcsGetThruLegs'
      operationId: dcs_v1_legs_legKey_thruLegs_get
      parameters:
      - name: legKey
        in: path
        required: true
        description: The leg key.
        schema:
          type: string
        x-position: 1
      responses:
        '200':
          description: List of legs that the specified leg has a direct downline connection to.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponseOfListOfLegInfo'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
              examples:
                Invalid legKey:
                  description: Example error response when the leg key is invalid.
                  value:
                    errors:
                    - id: a70ddb46-fc1a-bed4-9ae9-b3c4eb6be908
                      code: legKey:InvalidApiKey
                      message: 'Invalid legKey: asdf'
                      type: Validation
                      details:
                        message: 'Invalid legKey: asdf'
                        param: legKey
                        validation: InvalidApiKey
                      rawMessage: null
                      exception: null
                      debugMode: The API is currently running in debug mode. In production the 'rawMessage' and 'exception' nodes will not be returned. These are for troubleshooting development issues only.
                    data: null
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IJsonResponse'
components:
  schemas:
    OperationPayload:
      type: object
      additionalProperties: false
      properties:
        type:
          type:
          - string
          - 'null'
          description: "The type of payload this model represents, expressed as a single\ncharacter.\nPlease note that this should be a char and not a string.\n            "
          maxLength: 1
        compartment:
          type:
          - string
          - 'null'
          description: "The compartment for the payload this model represents, expressed\nas a single character.\nPlease note that this should be a char and not a string.\n            "
          maxLength: 1
        count:
          type: integer
          description: "The payload count.\n            "
          format: int32
        weight:
          type: integer
          description: "The total payload weight.\n            "
          format: int32
    OperationComment:
      type: object
      additionalProperties: false
      properties:
        commentKey:
          type:
          - string
          - 'null'
          description: "The unique identification number for the comment.\n            "
        text:
          type:
          - string
          - 'null'
          description: "Represents the comment text.\n            "
        type:
          description: "Represents the comment type.\n            "
          $ref: '#/components/schemas/OperationCommentType'
        createdDate:
          type: string
          description: "Represents the datetime (UTC) of when the comment was created.\n            "
          format: date-time
        modifiedDate:
          type: string
          description: "Represents the datetime (UTC) of when the comment was last modified.\n            "
          format: date-time
    IJsonResponseOfListOfLegCloseSecurityRequirement:
      type: object
      additionalProperties: false
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/LegCloseSecurityRequirement'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Message'
    OperationCommentType:
      type: integer
      description: "The operation comment type enumeration.\n            \n\n0 = Default\n1 = Reservation\n2 = Operation\n3 = PitLoad\n4 = Irop\n5 = AppsOverride\n6 = ManualAppsOverride"
      x-enumNames:
      - Default
      - Reservation
      - Operation
      - PitLoad
      - Irop
      - AppsOverride
      - ManualAppsOverride
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    OperationHistory:
      type: object
      additionalProperties: false
      properties:
        historyKey:
          type:
          - string
          - 'null'
          description: "The unique identification for the trip operation history.\n            "
        code:
          type:
          - string
          - 'null'
          description: "Represents the code for the event that triggered an entry into history.\n            "
        detail:
          type:
          - string
          - 'null'
          description: "Represents the history details.\n            "
        createdDate:
          type:
          - string
          - 'null'
          description: "The date when this history item was created.\n            "
          format: date-time
    OperationCounts:
      type: object
      additionalProperties: false
      properties:
        capacityCount:
          type: integer
          description: 'The number of passengers that can be seated in the aircraft.  This does not include

            cabin crew or cockpit crew.'
          format: int32
        soldCount:
          type: integer
          description: The number of seats sold.
          format: int32
        nonRevenueCount:
          type: integer
          description: The number of non-revenue passengers.
        revenueCount:
          type: integer
          description: The number of revenue passengers.
        infantCount:
          type: integer
          description: The number of infants not occupying a seat.
        checkInCount:
          type: integer
          description: 'The number of passengers that have checked in.  This value is called CheckedInCount in

            the response of GET api/dcs/v1/legs.'
        noShowCount:
          type: integer
          description: The number of passengers that have not checked in.
          format: int32
        boardingCount:
          type: integer
          description: 'The number of passengers that have boarded.  This value is called BoardedCount in

            the response of GET api/dcs/v1/legs.'
        boardingSequence:
          type: integer
          description: The last boarding sequence number used for a passenger on this leg.
        fuelOnboardOut:
          type: integer
          description: The amount of fuel onboard the aircraft upon departure.
          format: int32
        fuelOnboardIn:
          type: integer
          description: The amount of fuel onboard the aircraft upon arrival.
          format: int32
        upliftFuel:
          type: integer
          description: The amount of fuel loaded onto the aircraft before takeoff.
          format: int32
        upliftWeight:
          type: integer
          description: The weight of fuel loaded onto the aircraft before takeoff.
          format: int32
        cockpitCrewCount:
          type: integer
          description: The number of crew in the cockpit.
        cabinCrewCount:
          type: integer
          description: The number of crew in the cabin.
    OperationDelay:
      type: object
      additionalProperties: false
      properties:
        delayKey:
          type:
          - string
          - 'null'
          description: "The unique identification for the trip operation delay.\n            "
        createdDate:
          type:
          - string
          - 'null'
          description: "The date the status was created.\n            "
          format: date-time
        code:
          type:
          - string
          - 'null'
          description: "The delay code.\n            "
        minutes:
          type: integer
          description: "The number of minutes for this delay.\n            "
        note:
          type:
          - string
          - 'null'
          description: "The note for this delay, containing extra information about the delay\n(if any).\n            "
        includeMvtMessage:
          type: boolean
          description: "The flag to include the MVT message.\n            "
    DepartureStatus:
      type: integer
      description: '0 = Default

        1 = Cancelled

        2 = Boarding

        3 = SeeAgent

        4 = Delayed

        5 = Departed'
      x-enumNames:
      - Default
      - Cancelled
      - Boarding
      - SeeAgent
      - Delayed
      - Departed
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    LegCloseSecurityRequirement:
      type: object
      additionalProperties: false
      properties:
        governmentProgram:
          type:
          - string
          - 'null'
          description: The name of the government program.
        governmentProgramType:
          description: The type of the government program.
          $ref: '#/components/schemas/GovernmentProgramType'
        programDescription:
          type:
          - string
          - 'null'
          description: A description of the government program.
        eligibleDocuments:
          type:
          - array
          - 'null'
          description: 'A list of documents that are eligible for satisfying the goverment program. '
          items:
            $ref: '#/components/schemas/DocumentRequirement'
        documentRequiredFields:
          type:
          - array
          - 'null'
          description: 'A list of document fields that are required for a document to contain in order to satisfy the government program. '
          items:
            $ref: '#/components/schemas/GovernmentDocumentFieldType'
        additionalDataRequiredFields:
          type:
          - array
          - 'null'
          description: 'A list of additional data fields that are required to satisfy the government program.  '
          items:
            $ref: '#/components/schemas/GovernmentAdditionalDataType'
        minVerifiedDocumentCount:
          type: integer
          description: 'The minimum amount of eligible documents needed to safisty the government program.  '
          format: int32
        flightCloseCountryCodes:
          type:
          - array
          - 'null'
          description: 'The list of country codes in which the government program requirement applies. More information on a given country code can be found via GET /api/nsk/v2/resources/countries/{countryCode}  '
          items:
            type: string
    Exception:
      type: object
      additionalProperties: false
      properties:
        Message:
          type: string
        InnerException:
          $ref: '#/components/schemas/Exception'
        Source:
          type:
          - string
          - 'null'
        StackTrace:
          type:
          - string
          - 'null'
    CrewType:
      type: integer
      description: "Defines the different types of crew members.\n            \n\n0 = Default\n1 = Pilot\n2 = CoPilot\n3 = CockpitJumpseat\n4 = CabinJumpseat\n5 = CabinCrew"
      x-enumNames:
      - Default
      - Pilot
      - CoPilot
      - CockpitJumpseat
      - CabinJumpseat
      - CabinCrew
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    GovernmentAdditionalDataType:
      type: integer
      description: '0 = CountryOfResidence

        1 = InTransitAtOrigin

        2 = InTransitAtDestination

        3 = DateOfBirth

        4 = Gender

        5 = FirstName

        6 = LastName

        7 = StayType

        8 = Nationality'
      x-enumNames:
      - CountryOfResidence
      - InTransitAtOrigin
      - InTransitAtDestination
      - DateOfBirth
      - Gender
      - FirstName
      - LastName
      - StayType
      - Nationality
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    LegInfo:
      type: object
      additionalProperties: false
      properties:
        carrierCode:
          type:
          - string
          - 'null'
        flightNumber:
          type:
          - string
          - 'null'
        opSuffix:
          type:
          - string
          - 'null'
        origin:
          type:
          - string
          - 'null'
        destination:
          type:
          - string
          - 'null'
        departureTime:
          type: string
          format: date-time
        arrivalTime:
          type: string
          format: date-time
        legKey:
          type:
          - string
          - 'null'
        manifestLegKey:
          type:
          - string
          - 'null'
    MessageStatus:
      type: integer
      description: '0 = General

        1 = Warning

        2 = Critical'
      x-enumNames:
      - General
      - Warning
      - Critical
      enum:
      - 0
      - 1
      - 2
    Leg:
      type: object
      additionalProperties: false
      properties:
        legKey:
          type:
          - string
          - 'null'
        manifestLegKey:
          type:
          - string
          - 'null'
        carrierCode:
          type:
          - string
          - 'null'
        flightNumber:
          type:
          - string
          - 'null'
        opSuffix:
          type:
          - string
          - 'null'
        origin:
          type:
          - string
          - 'null'
        destination:
          type:
          - string
          - 'null'
        departureTime:
          type: string
          format: date-time
        arrivalTime:
          type: string
          format: date-time
        codeShareIndicator:
          $ref: '#/components/schemas/CodeShareIndicator'
        operatingCarrierCode:
          type:
          - string
          - 'null'
        operatingFlightNumber:
          type:
          - string
          - 'null'
        operatingOpSuffix:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/LegStatus'
        estimatedDepartureGate:
          type:
          - string
          - 'null'
        actualDepartureGate:
          type:
          - string
          - 'null'
        isVerified:
          type: boolean
        capacityCount:
          type: integer
          description: The capacity of the aircraft/equipment.
          format: int32
        soldCount:
          type: integer
          description: The number of seats sold.
          format: int32
        checkedInCount:
          type: integer
          description: The number of passengers that have checked in.
          format: int32
        boardedCount:
          type: integer
          description: The number of passengers that have boarded.
          format: int32
        noShowCount:
          type: integer
          description: The number of passengers that have not checked in.
          format: int32
    IJsonResponseOfOperationsInfo:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/OperationsInfo'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Message'
    CodeShareIndicator:
      type: integer
      description: 'Specifies the type of code share agreement.


        0 = NonCodeShare

        1 = CodeShareCommercialDuplicate

        2 = SharedDesignatorOrWetLease

        3 = CodeShareHostOperatingCarrier

        4 = CodeShareCommercialDuplicateWithOverrideText

        5 = SharedDesignatorOrWetLeaseWithOverrideText'
      x-enumNames:
      - NonCodeShare
      - CodeShareCommercialDuplicate
      - SharedDesignatorOrWetLease
      - CodeShareHostOperatingCarrier
      - CodeShareCommercialDuplicateWithOverrideText
      - SharedDesignatorOrWetLeaseWithOverrideText
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    DocumentGroup:
      type: integer
      description: 'Corresponds to what NewSkies calls the DocumentType (which is different from the

        DocumentTypeCode).


        0 = Unknown

        1 = AlienRegistrationCard

        2 = PermanentResidentCard

        3 = FacilitationDocument

        4 = InsPass

        5 = MilitaryId

        6 = Passport

        7 = ReEntryPermit

        8 = CreditCard

        9 = TravelVisa

        10 = OAFrequentFlyer

        11 = ParoleLetter

        12 = NoticeOfAction

        13 = TransportationLetter

        14 = BorderCrossingCard

        15 = PilotLicense

        16 = USNaturalizationCertificate

        17 = RefugeeTravelDocument

        18 = GovernmentId

        19 = DriversLicense

        20 = RedressNumber

        21 = KnownTravelerId

        22 = FormOfId

        23 = Nexus

        24 = SecondaryExempt'
      x-enumNames:
      - Unknown
      - AlienRegistrationCard
      - PermanentResidentCard
      - FacilitationDocument
      - InsPass
      - MilitaryId
      - Passport
      - ReEntryPermit
      - CreditCard
      - TravelVisa
      - OAFrequentFlyer
      - ParoleLetter
      - NoticeOfAction
      - TransportationLetter
      - BorderCrossingCard
      - PilotLicense
      - USNaturalizationCertificate
      - RefugeeTravelDocument
      - GovernmentId
      - DriversLicense
      - RedressNumber
      - KnownTravelerId
      - FormOfId
      - Nexus
      - SecondaryExempt
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
    LegStatus:
      type: integer
      description: '0 = Blocked

        1 = Boarding

        2 = BoardingClosedPending

        3 = Canceled

        4 = Delayed

        5 = Departed

        6 = DepartedClosed

        7 = DepartedClosedPending

        8 = OnTime

        9 = Closed

        10 = OnTimeClosedPending

        11 = Early

        12 = Suspended

        13 = EarlyClosedPending

        14 = DelayedClosedPending'
      x-enumNames:
      - Blocked
      - Boarding
      - BoardingClosedPending
      - Canceled
      - Delayed
      - Departed
      - DepartedClosed
      - DepartedClosedPending
      - OnTime
      - Closed
      - OnTimeClosedPending
      - Early
      - Suspended
      - EarlyClosedPending
      - DelayedClosedPending
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
    GovernmentProgramType:
      type: integer
      description: '0 = None

        1 = Aqq

        2 = SecureFlight

        3 = Apps

        4 = Apis

        5 = Iapp

        6 = Eub

        7 = Iatci

        8 = DocCheck

        9 = DocsOnly

        10 = Pnrgov

        11 = DigiYatra

        12 = Pfms'
      x-enumNames:
      - None
      - Aqq
      - SecureFlight
      - Apps
      - Apis
      - Iapp
      - Eub
      - Iatci
      - DocCheck
      - DocsOnly
      - Pnrgov
      - DigiYatra
      - Pfms
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    OperationalTimes:
      type: object
      additionalProperties: false
      properties:
        estimatedTouchDownTime:
          type:
          - string
          - 'null'
          description: "Represents the estimated touch down time.\n            "
          format: date-time
        actualTouchDownTime:
          type:
          - string
          - 'null'
          description: "Represents the actual touch down time.\n            "
          format: date-time
        forcedTouchDownTime:
          type:
          - string
          - 'null'
          description: "Represents the forced touch down time.\n            "
          format: date-time
        estimatedOnBlockTime:
          type:
          - string
          - 'null'
          description: "Represents the estimated on block time.\n            "
          format: date-time
        actualOnBlockTime:
          type:
          - string
          - 'null'
          description: "Represents the actual on block time.\n            "
          format: date-time
        forcedOnBlockTime:
          type:
          - string
          - 'null'
          description: "Represents the forced on block time.\n            "
          format: date-time
        estimatedDepartureTime:
          type:
          - string
          - 'null'
          description: "Represents the estimated departure time.\n            "
          format: date-time
        offBlockTime:
          type:
          - string
          - 'null'
          description: "Represents the off-block time for this flight operation.\n            "
          format: date-time
        airborneTime:
          type:
          - string
          - 'null'
          description: "Represents the airborne time for this flight operation.\n            "
          format: date-time
        crewReportTime:
          type:
          - string
          - 'null'
          description: "Represents the crew report time for this flight operation.\n            "
          format: date-time
        takeOffTime:
          type:
          - string
          - 'null'
          description: "Represents the take-off time for this flight operation.\n            "
          format: date-time
        movementAfterPushBackTime:
          type:
          - string
          - 'null'
          description: "Represents the movement after push-back time (taxi) for this flight operation.\n            "
          format: date-time
        nextInformationTime:
          type:
          - string
          - 'null'
          description: "Represents the next information time for this flight operation.\n            "
          format: date-time
        reclearanceTime:
          type:
          - string
          - 'null'
          description: "Represents the re-clearance time for this flight operation.\n            "
          format: date-time
        returnToRampTime:
          type:
          - string
          - 'null'
          description: "Represents the return to ramp time for this flight operation.\n            "
          format: date-time
    GovernmentDocumentFieldType:
      type: integer
      description: '0 = FirstName

        1 = MiddleName

        2 = LastName

        3 = Title

        4 = Suffix

        5 = DateOfBirth

        6 = BirthCountry

        7 = Gender

        8 = Nationality

        9 = Number

        10 = IssuingCountry

        11 = ExpirationDate

        12 = IssuedDate

        13 = Verified'
      x-enumNames:
      - FirstName
      - MiddleName
      - LastName
      - Title
      - Suffix
      - DateOfBirth
      - BirthCountry
      - Gender
      - Nationality
      - Number
      - IssuingCountry
      - ExpirationDate
      - IssuedDate
      - Verified
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
    ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        exception:
          $ref: '#/components/schemas/Exception'
        rawMessage:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        number:
          type:
          - integer
          - 'null'
          format: int32
          maximum: 99999.0
          minimum: 0.0
        details:
          type:
          - object
          - 'null'
          additionalProperties:
            type: string
        ActivityId:
          type:
          - string
          - 'null'
    IJsonResponseOfListOfLeg:
      type: object
      additionalProperties: false
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Leg'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Message'
    Message:
      type: object
      additionalProperties: false
      properties:
        code:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        value:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/MessageStatus'
        details:
          type:
          - object
          - 'null'
          additionalProperties:
            type: string
    ArrivalStatus:
      type: integer
      description: '0 = Default

        1 = Cancelled

        2 = Arrived

        3 = SeeAgent

        4 = Delayed'
      x-enumNames:
      - Default
      - Cancelled
      - Arrived
      - SeeAgent
      - Delayed
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
    DocumentRequirement:
      type: object
      additionalProperties: false
      properties:
        typeCode:
          type:
          - string
          - 'null'
          description: The type code of the document
        group:
          description: 'Corresponds to what NewSkies calls the DocumentType (which is different from the

            DocumentTypeCode).'
          $ref: '#/components/schemas/DocumentGroup'
        typeName:
          type:
          - string
          - 'null'
          description: The type name of the document
        isPrimary:
          type: boolean
          description: Whether or not the document can be considered a primary document.
    IJsonResponse:
      type: object
      additionalProperties: false
      properties:
        data: {}
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Message'
    OperationsInfo:
      type: object
      additionalProperties: false
      properties:
        legKey:
          type:
          - string
          - 'null'
        manifestLegKey:
          type:
          - string
          - 'null'
        carrierCode:
          type:
          - string
          - 'null'
        flightNumber:
          type:
          - string
          - 'null'
        opSuffix:
          type:
          - string
          - 'null'
        origin:
          type:
          - string
          - 'null'
        destination:
          type:
          - string
          - 'null'
        departureTime:
          type: string
          format: date-time
        arrivalTime:
          type: string
          format: date-time
        isPassive:
          type: boolean
          description: "Specifies whether this leg belongs to a passive segment.\n            "
        status:
          description: "The calculated status of the flight.\n            "
          $ref: '#/components/schemas/LegStatus'
        departureStatus:
          description: "Represents the departure status.\n            "
          $ref: '#/components/schemas/DepartureStatus'
        departureNote:
          type:
          - string
          - 'null'
          description: "Represents additional information about the\ntrip operation station.\n            "
        estimatedDepartureGate:
          type:
          - string
          - 'null'
          description: "Represents the gate details.\n            "
        actualDepartureGate:
          type:
          - string
          - 'null'
          description: "Represents the actual gate of the trip mode.\n            "
        arrivalStatus:
          description: "Represents the arrival status.\n            "
          $ref: '#/components/schemas/ArrivalStatus'
        arrivalNote:
          type:
          - string
          - 'null'
          description: "Represents additional information about the\ntrip operation station.\n            "
        estimatedArrivalGate:
          type:
          - string
          - 'null'
          description: "Represents the gate details.\n            "
        actualArrivalGate:
          type:
          - string
          - 'null'
          description: "Represents the actual gate of the trip mode.\n            "
        baggageClaim:
          type:
          - string
          - 'null'
          description: "Represents the airline defined location where the trip's\nluggage is to be retrieved.\n            "
        operationalTimes:
          description: "List of operational times.\n            "
          $ref: '#/components/schemas/OperationalTimes'
        tailNumber:
          type:
          - string
          - 'null'
          description: "Represents the tail number for the aircraft.\n            "
        equipmentType:
          type:
          - string
          - 'null'
          description: "Represents the equipment type for the leg.\n            "
        equipmentTypeSuffix:
          type:
          - string
          - 'null'
          description: "Represents the equipment type suffix for the leg.\n            "
        modifiedAgentName:
          type:
          - string
          - 'null'
          description: "The name of the agent that last modified this data.\n            "
        isVerified:
          type: boolean
          description: "Represents the verified bit.\n            "
        isIrop:
          type: boolean
          description: "Represents the IROP flag.\n            "
        operationCounts:
          description: "Represents the various counts related to the operation.\n            "
          $ref: '#/components/schemas/OperationCounts'
        comments:
          type:
          - array
          - 'null'
          description: "Represents the comments related to this trip operation.\n            "
          items:
            $ref: '#/components/schemas/OperationComment'
        delays:
          type:
          - array
          - 'null'
          description: "A list of trip operation delays.\n            "
          items:
            $ref: '#/components/schemas/OperationDelay'
        payloads:
          type:
          - array
          - 'null'
          description: "Represents the list of trip operation payloads.\n            "
          items:
            $ref: '#/components/schemas/OperationPayload'
        crewList:
          type:
          - array
          - 'null'
          description: "Represents the list of crew members.\n            "
          items:
            $ref: '#/components/schemas/OperationCrew'
        historyList:
          type:
          - array
          - 'null'
          description: "Represents the history of this trip operation.\n            "
          items:
            $ref: '#/components/schemas/OperationHistory'
        boardingTimeOffset:
          type: integer
          description: "Represents the number of minutes before a flight departs that boarding is scheduled to begin. \n            "
    OperationCrew:
      type: object
      additionalProperties: false
      properties:
        crewKey:
          type:
          - string
          - 'null'
          description: "The unique identifier for the trip crew operation.\n            "
        type:
          description: "The crew personnel type.\n            "
          $ref: '#/components/schemas/CrewType'
    IJsonResponseOfListOfLegInfo:
      type: object
      additionalProperties: false
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/LegInfo'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorResponse'
        messages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Message'
  securitySchemes:
    JWT:
      type: http
      description: Paste your JWT token from the token endpoint.
      scheme: bearer
      bearerFormat: jwt
x-generator: NSwag v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))
